#Make your own logo 
print("=============================================================")
print("|                 ROBADISHONGE INDUSTRIES                   |")
print("|                                                           |")
print("|                     FOUNDED IN 2004                       |")
print("|                                                           |")
print("|               MISSION IS TO IMPACT THE WORLD              |")
print("|                                                           |")
print("|               LET US DO ALL THE WORK FOR YOU              |")
print("=============================================================")  	