#write a program to display a big T
print("====================")
print("          ||        ")
print("          ||        ")
print("          ||        ")
print("          ||        ")
print("          ||        ")
print("          ||        ")
print("          ||        ")
print("          ||        ")
print("          ||        ")
print("          ||        ")
print("          ||        ")