f_name = input("What is your first name?")
s_name = input("What is your second name?")
print("My first name is :",f_name)
print("My second name is :",s_name)
name = input("What is your name?")
f_num = input("Enter first number")
s_num = input("Enter second number")
sum_num = f_num + s_num
print("The sum of the numbers is :",sum_num)
#convert the string into integers
sum_num = int(f_num) + int(s_num)
diff_num = int(f_num) - int(s_num)
quot_num = int(f_num) / int(s_num)
prod_num  = int(f_num) * int(s_num)
print("The sum of the numbers is :",sum_num)
print("The diff of the numbers is :",diff_num)
print("The quot of the numbers is :",quot_num)
print("The prod of the numbers is :",prod_num)
